# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the serv er process.

# Site settings
title: Placeholder
email: monstrefou@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Super duper blog about suffs
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://localhost:4000" # the base hostname & protocol for your site
url: "http://lapinozz.github.io" # the base hostname & protocol for your site
#twitter_username: lapinozz
github_username: lapinozz
#facebook_username: lapinozz

# Gems
plugins:
- jekyll-archives
- jekyll-paginate
- jekyll-sitemap

# Config
paginate: 5
paginate_path: "page/:num"
# Build settings
markdown: kramdown
timezone: Canada/Eastern

# Archive
jekyll-archives:
  enabled: []
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
